language: java
jdk: openjdk8

jobs:
  include:
    - os: linux
      dist: xenial
    - os: linux
      dist: bionic
    - os: osx
      osx_image: xcode9.3

intall: mvn install -DskipTests=true -B -V
script: mvn test -B
