language: java
jdk: openjdk8

jobs:
  include:
    - os: linux
      dist: xenial
    - os: linux
      dist: bionic
    - os: osx
      osx_image: xcode9.2

intall:
    - ls -la test_files/
    - mvn install -DskipTests=true -B -V
script: mvn test -B
